# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Count2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1178, 609)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, -10, 1181, 641))
        self.background.setAcceptDrops(False)
        self.background.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.background.setAutoFillBackground(True)
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("CPENT-master\images\count_image.jpg"))
        self.background.setScaledContents(True)
        self.background.setOpenExternalLinks(False)
        self.background.setObjectName("background")
        
        self.view = QtWidgets.QLabel(self.centralwidget)
        self.view.setGeometry(QtCore.QRect(270, 130, 600, 450))
        self.view.setStyleSheet("background-color: rgb(157, 157, 157);")
        self.view.setText("")
        self.view.setObjectName("view")
        
        self.curls = QtWidgets.QPushButton(self.centralwidget)
        self.curls.setGeometry(QtCore.QRect(60, 150, 171, 51))
        
        self.curls.setStyleSheet(u"background-color:#7689de;\n"
"color:#a9dce3;\n"
"border-style: outset;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-color:black;\n"
"font:bold 25px;\n"
"padding :6px;\n"
"min-width:10px;\n"
"")
        self.curls.setObjectName("curls")
        self.abs = QtWidgets.QPushButton(self.centralwidget)
        self.abs.setGeometry(QtCore.QRect(60, 230, 171, 51))
        self.abs.setStyleSheet(u"background-color:#7689de;\n"
"color:#a9dce3;\n"
"border-style: outset;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-color:black;\n"
"font:bold 25px;\n"
"padding :6px;\n"
"min-width:10px;\n"
"")
        self.abs.setObjectName("abs")
        self.pushup = QtWidgets.QPushButton(self.centralwidget)
        self.pushup.setGeometry(QtCore.QRect(60, 310, 171, 51))
        self.pushup.setStyleSheet(u"background-color:#7689de;\n"
"color:#a9dce3;\n"
"border-style: outset;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-color:black;\n"
"font:bold 25px;\n"
"padding :6px;\n"
"min-width:10px;\n"
"")
        self.pushup.setObjectName("pushup")
        self.squats = QtWidgets.QPushButton(self.centralwidget)
        self.squats.setGeometry(QtCore.QRect(60, 390, 171, 51))
        self.squats.setStyleSheet(u"background-color:#7689de;\n"
"color:#a9dce3;\n"
"border-style: outset;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-color:black;\n"
"font:bold 25px;\n"
"padding :6px;\n"
"min-width:10px;\n"
"")
        self.squats.setObjectName("squats")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(60, 490, 171, 51))
        self.back.setStyleSheet(u"background-color:#7689de;\n"
"color:#a9dce3;\n"
"border-style: outset;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-color:black;\n"
"font:bold 25px;\n"
"padding :6px;\n"
"min-width:10px;\n"
"")
        self.back.setObjectName("back")
        
        self.information = QtWidgets.QLabel(self.centralwidget)
        self.information.setGeometry(QtCore.QRect(890, 130, 261, 241))
        self.information.setStyleSheet("background-color: rgb(157, 157, 157);")
        self.information.setText("")
        self.information.setObjectName("information")
        
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(890, 390, 91, 51))
        self.start.setStyleSheet(u"background-color:#7689de;\n"
"color:#a9dce3;\n"
"border-style: outset;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-color:black;\n"
"font:bold 25px;\n"
"padding :6px;\n"
"min-width:10px;\n"
"")
        self.start.setObjectName("start")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(1030, 450, 111, 91))
        self.lcdNumber.setObjectName("lcdNumber")
        
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(870, 470, 121, 61))
        self.label_2.setStyleSheet("border-color: rgb(255, 170, 0);\n"
"font: 45 48pt \"Calibri\";\n"
"color: rgb(255, 255, 255);\n"
"font:30pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        
        self.timeLabel = QtWidgets.QLabel(self.centralwidget)
        self.timeLabel.setGeometry(QtCore.QRect(1020, 380, 121, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.timeLabel.setFont(font)
        self.timeLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.timeLabel.setObjectName("timeLabel")
        
        self.radioR = QtWidgets.QRadioButton(self.centralwidget)
        self.radioR.setGeometry(QtCore.QRect(290, 150, 141, 31))
        self.radioR.setObjectName("radioR")
        self.radioL = QtWidgets.QRadioButton(self.centralwidget)
        self.radioL.setGeometry(QtCore.QRect(290, 180, 141, 31))
        self.radioL.setObjectName("radioL")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))       
        self.curls.setText(_translate("MainWindow", "CURLS"))
        self.abs.setText(_translate("MainWindow", "LEG RAISE"))
        self.pushup.setText(_translate("MainWindow", "PUSH UP"))
        self.squats.setText(_translate("MainWindow", "SQUATS"))
        self.back.setText(_translate("MainWindow", "BACK"))
        self.start.setText(_translate("MainWindow", "STOP"))
        self.radioR.setText(_translate("MainWindow", "RIGHT"))
        self.radioL.setText(_translate("MainWindow", "LEFT"))
        
        self.timeLabel.setText(_translate("MainWindow", "00:00"))
        self.label_2.setText(_translate("MainWindow", " REP"))
import yoga1_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
